package com.iakay.scoo.dao.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.iakay.scoo.enumeration.ALERT;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Created by iakay on 2020-01-02.
 */
@Data
@DynamoDBTable(tableName = "Pricing")
public class Alert {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String userId;
    @DynamoDBAttribute
    private String scooterId;
    @DynamoDBAttribute
    private String ridingId;
    @DynamoDBAttribute
    private String problemId;
    @DynamoDBAttribute
    private ALERT type;
    @DynamoDBAttribute
    private String detail;
    @DynamoDBAttribute
    private LocalDateTime dateTime;
}
