package com.iakay.scoo.dao.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.iakay.scoo.enumeration.PICTURE_REASON;
import com.iakay.scoo.enumeration.SUCCESS;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Created by iakay on 2020-01-02.
 */
@Data
@DynamoDBTable(tableName = "Picture")
public class Picture {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String ridingId;
    @DynamoDBAttribute
    private String problemId;
    @DynamoDBAttribute
    private PICTURE_REASON reason;
    @DynamoDBAttribute
    private LocalDateTime dateTime;
}
