package com.iakay.scoo.dao.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.iakay.scoo.enumeration.PROBLEM_TYPE;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Created by iakay on 2020-01-02.
 */
@Data
@DynamoDBTable(tableName = "ProblemReporting")
public class ProblemReporting {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String userId;
    @DynamoDBAttribute
    private String scooterId;
    @DynamoDBAttribute
    private String ridingId;
    @DynamoDBAttribute
    private PROBLEM_TYPE problemType;
    @DynamoDBAttribute
    private String detail;
    @DynamoDBAttribute
    private LocalDateTime dateTime;
    @DynamoDBAttribute
    private double coordinate;
    @DynamoDBAttribute
    private String pictureId;
}
