package com.iakay.scoo.dao.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.iakay.scoo.enumeration.RIDING_STATUS;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Created by iakay on 2020-01-02.
 */
@Data
@DynamoDBTable(tableName = "RidingCoordinates")
public class RidingCoordinates {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String ridingId;
    @DynamoDBAttribute
    private double coordinate;
    @DynamoDBAttribute
    private RIDING_STATUS status;
    @DynamoDBAttribute
    private double distance;
    @DynamoDBAttribute
    private LocalDateTime dateTime;
}
