package com.iakay.scoo.dao.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.iakay.scoo.enumeration.BAND;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Created by iakay on 2020-01-02.
 */
@Data
@DynamoDBTable(tableName = "Scooter")
public class Scooter {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private BAND band;
    @DynamoDBAttribute
    private LocalDateTime recordDateTime;
    @DynamoDBAttribute
    private double purchaseValue;
    @DynamoDBAttribute
    private String gpsId;
    @DynamoDBAttribute
    private int gpsPhoneNumber;
    @DynamoDBAttribute
    private String lockId;
    @DynamoDBAttribute
    private int lockPassword;

}
