package com.iakay.scoo.dao.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.iakay.scoo.enumeration.SCOOTER_ACTION;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Created by iakay on 2020-01-02.
 */
@Data
@DynamoDBTable(tableName = "ScooterLog")
public class ScooterLog {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String scooterId;
    @DynamoDBAttribute
    private SCOOTER_ACTION action;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute
    private LocalDateTime date;
}
