package com.iakay.scoo.dao.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.iakay.scoo.enumeration.USER_ACTION;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Created by iakay on 2020-01-02.
 */
@Data
@DynamoDBTable(tableName = "UserLog")
public class UserLog {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;
    @DynamoDBAttribute
    private USER_ACTION action;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute
    private LocalDateTime dateTime;
}
